In [1]:
import pandas as pd
pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,E0,26/02/2022,15:00,Man United,Watford,0,0,D,0,0,...,2.15,-1.25,1.87,2.03,1.88,2.05,1.91,2.19,1.86,2.03
253,E0,26/02/2022,15:30,Brighton,Aston Villa,0,2,A,0,1,...,1.70,-0.25,1.91,1.99,1.93,2.00,1.96,2.02,1.90,1.97
254,E0,26/02/2022,17:30,Everton,Man City,0,1,A,0,0,...,2.50,1.75,1.92,1.98,2.01,1.89,2.05,1.99,1.95,1.92
255,E0,27/02/2022,14:00,West Ham,Wolves,1,0,H,0,0,...,1.63,-0.50,1.94,1.96,1.94,1.98,1.97,2.00,1.94,1.94
256,E0,01/03/2022,19:45,Burnley,Leicester,0,2,A,0,0,...,1.81,0.25,1.75,2.17,1.74,2.23,1.85,2.26,1.73,2.18

In [5]:
root = 'https://www.football-data.co.uk/mmz4281/'
# creating list of leagues
leagues = ['E0', 'E1']
# looping through leagues, reading multiple csv and appending it into a list
frames = []
for league in leagues:
    df = pd.read_csv(root + "2122" + "/"  + league + ".csv")
    frames.append(df)

In [16]:
l0 = frames[0]
l0

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,E0,26/02/2022,15:00,Man United,Watford,0,0,D,0,0,...,2.15,-1.25,1.87,2.03,1.88,2.05,1.91,2.19,1.86,2.03
253,E0,26/02/2022,15:30,Brighton,Aston Villa,0,2,A,0,1,...,1.70,-0.25,1.91,1.99,1.93,2.00,1.96,2.02,1.90,1.97
254,E0,26/02/2022,17:30,Everton,Man City,0,1,A,0,0,...,2.50,1.75,1.92,1.98,2.01,1.89,2.05,1.99,1.95,1.92
255,E0,27/02/2022,14:00,West Ham,Wolves,1,0,H,0,0,...,1.63,-0.50,1.94,1.96,1.94,1.98,1.97,2.00,1.94,1.94
256,E0,01/03/2022,19:45,Burnley,Leicester,0,2,A,0,0,...,1.81,0.25,1.75,2.17,1.74,2.23,1.85,2.26,1.73,2.18

In [15]:
l1 = frames[1]
l1

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E1,06/08/2021,19:45,Bournemouth,West Brom,2,2,D,1,1,...,1.84,-0.25,2.13,1.78,2.13,1.80,2.16,1.83,2.09,1.77
1,E1,07/08/2021,15:00,Blackburn,Swansea,2,1,H,1,0,...,1.70,-0.25,1.77,2.14,1.83,2.09,1.87,2.17,1.81,2.04
2,E1,07/08/2021,15:00,Bristol City,Blackpool,1,1,D,1,0,...,1.66,-0.25,1.90,2.00,1.92,1.99,1.92,2.01,1.89,1.95
3,E1,07/08/2021,15:00,Cardiff,Barnsley,1,1,D,0,0,...,1.62,-0.25,2.05,1.75,2.14,1.80,2.19,1.80,2.11,1.75
4,E1,07/08/2021,15:00,Derby,Huddersfield,1,1,D,1,1,...,1.60,-0.25,1.88,2.02,1.88,2.01,1.90,2.07,1.87,1.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,E1,26/02/2022,15:00,Millwall,Sheffield United,1,0,H,0,0,...,1.58,0.25,1.84,2.06,1.79,2.14,1.90,2.14,1.82,2.04
400,E1,26/02/2022,15:00,Nott'm Forest,Bristol City,2,0,H,1,0,...,2.00,-0.75,1.97,1.93,1.99,1.92,2.03,1.94,1.97,1.88
401,E1,26/02/2022,15:00,Peterboro,Hull,0,3,A,0,1,...,1.67,0.00,1.87,2.03,1.95,1.95,1.99,2.03,1.91,1.93
402,E1,28/02/2022,20:00,West Brom,Swansea,0,2,A,0,0,...,1.72,-0.75,1.94,1.96,1.91,1.99,1.97,2.07,1.90,1.95
403,E1,01/03/2022,19:45,Cardiff,Derby,1,0,H,0,0,...,1.49,-0.50,2.04,1.86,2.06,1.85,2.11,1.87,2.06,1.80

In [19]:
df = l0.append(l1, ignore_index=True)
df.shape

(661, 106)

In [20]:
df.dtypes

Div          object
Date         object
Time         object
HomeTeam     object
AwayTeam     object
             ...
PCAHA       float64
MaxCAHH     float64
MaxCAHA     float64
AvgCAHH     float64
AvgCAHA     float64
Length: 106, dtype: object

In [21]:
simpsons = pd.read_html('https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes_(seasons_1%E2%80%9320)')

In [24]:
# getting the first 5 rows of the table "Season 1"
simpsons[1].head()

,No.overall,No. inseason,Title,Directed by,Written by,Original air date,Prod.code,U.S. viewers(millions)
0,1,1,"""Simpsons Roasting on an Open Fire""",David Silverman,Mimi Pond,"DecemberÂ 17,Â 1989",7G08,26.7[46]
1,2,2,"""Bart the Genius""",David Silverman,Jon Vitti,"JanuaryÂ 14,Â 1990",7G02,24.5[46]
2,3,3,"""Homer's Odyssey""",Wesley Archer,Jay Kogen & Wallace Wolodarsky,"JanuaryÂ 21,Â 1990",7G03,27.5[47]
3,4,4,"""There's No Disgrace Like Home""",Gregg Vanzo & Kent Butterworth,Al Jean & Mike Reiss,"JanuaryÂ 28,Â 1990",7G04,20.2[48]
4,5,5,"""Bart the General""",David Silverman,John Swartzwelder,"FebruaryÂ 4,Â 1990",7G05,27.1[49]