In [38]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from sqlalchemy import create_engine

engine1 = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

In [48]:
df = pd.read_csv("../data/div-20q4.csv", parse_dates=['xd_date','pay_date'],
                dtype={'name':'string','shares':'int'},nrows=41)
df.dtypes

name                string
qtr                 object
shares               int32
dividend            object
net                 object
xd_date     datetime64[ns]
pay_date    datetime64[ns]
dtype: object

In [49]:
df

      name      qtr  shares    dividend         net    xd_date   pay_date
0     DTAC  ฿2.1200    9000  ฿19,080.00  ฿17,172.00 2021-02-11 2021-04-20
1   ADVANC  ฿3.6800     600   ฿2,208.00   ฿1,987.20 2021-02-19 2021-04-20
2      DIF  ฿0.2610   80000  ฿20,880.00  ฿20,880.00 2021-02-23 2021-03-12
3    JASIF  ฿0.2500  130000  ฿32,500.00  ฿32,500.00 2021-02-24 2021-03-15
4     SCCC  ฿9.0000     600   ฿5,400.00   ฿4,860.00 2021-02-24 2021-05-04
5   GVREIT  ฿0.2037   18000   ฿3,666.60   ฿3,299.94 2021-02-25 2021-03-10
6       MC  ฿0.3500   10000   ฿3,500.00   ฿3,150.00 2021-02-25 2021-03-11
7    PTTGC  ฿1.0000    2000   ฿2,000.00   ฿1,800.00 2021-02-25 2021-04-23
8    CPTGF  ฿0.1800   10000   ฿1,800.00   ฿1,620.00 2021-03-01 2021-04-23
9   EGATIF  ฿0.2000   10000   ฿2,000.00   ฿2,000.00 2021-03-01 2021-03-17
10   HREIT  ฿0.0860   30000   ฿2,580.00   ฿2,322.00 2021-03-01 2021-03-30
11   TTLPF  ฿0.4300   11100   ฿4,773.00   ฿4,295.70 2021-03-01 2021-03-17
12   RATCH  ฿1.2500    6000   ฿7,500.00   ฿6,750.00 2021-03-02 2021-04-23
13   WHART  ฿0.1195   10000   ฿1,195.00   ฿1,075.50 2021-03-04 2021-03-22
14      TU  ฿0.4000   21000   ฿8,400.00   ฿7,770.00 2021-03-08 2021-04-21
15     UTP  ฿0.3900    6000   ฿2,340.00   ฿2,106.00 2021-03-08 2021-05-25
16    EGCO  ฿3.5000     900   ฿3,150.00   ฿2,835.00 2021-03-09 2021-04-27
17  FSMART  ฿0.3000   18000   ฿5,400.00   ฿4,860.00 2021-03-09 2021-04-29
18     TIP  ฿1.3000    3000   ฿3,900.00   ฿3,510.00 2021-03-11 2021-05-19
19   TPIPP  ฿0.1500   60000   ฿9,000.00   ฿9,000.00 2021-03-12 2021-05-07
20     TVO  ฿0.8000    6000   ฿4,800.00   ฿4,320.00 2021-03-12 2021-05-14
21     MCS  ฿0.6000   75000  ฿45,000.00  ฿43,050.00 2021-03-15 2021-04-28
22     PDG  ฿0.2200   25000   ฿5,500.00   ฿4,950.00 2021-03-15 2021-05-20
23    SMPC  ฿0.4300   20000   ฿8,600.00   ฿7,740.00 2021-04-04 2021-04-30
24     DCC  ฿0.0440   40000   ฿1,760.00   ฿1,584.00 2021-04-05 2021-04-27
25      GC  ฿0.4000   15000   ฿6,000.00   ฿5,400.00 2021-04-16 2021-04-30
26     BGC  ฿0.1200   10000   ฿1,200.00   ฿1,200.00 2021-04-21 2021-05-07
27    MBAX  ฿0.5600   12000   ฿6,720.00   ฿6,048.00 2021-04-21 2021-05-07
28   AMATA  ฿0.2000   12000   ฿2,400.00   ฿2,160.00 2021-04-22 2021-05-07
29   TISCO  ฿6.3000    2000  ฿12,600.00  ฿11,340.00 2021-04-28 2021-05-17
30   ASIAN  ฿0.5500   10000   ฿5,500.00   ฿4,450.00 2021-04-29 2021-05-17
31     PRM  ฿0.1800   33000   ฿5,940.00   ฿5,398.80 2021-04-30 2021-05-20
32    TCAP  ฿1.8000    3000   ฿5,400.00   ฿4,860.00 2021-04-30 2021-05-21
33  GUNKUL  ฿0.1820   30000   ฿5,460.00   ฿4,914.00 2021-05-06 2021-05-24
34     IVL  ฿0.1750   10000   ฿1,750.00   ฿1,575.00 2021-05-06 2021-05-20
35      LH  ฿0.3000   42000  ฿12,600.00  ฿11,340.00 2021-05-06 2021-05-21
36     ORI  ฿0.3900   50000  ฿19,500.00  ฿17,550.00 2021-05-07 2021-05-18
37   ROJNA  ฿0.2000   20000   ฿4,000.00   ฿3,600.00 2021-05-07 2021-05-25
38   NOBLE  ฿0.5000   12000   ฿6,000.00   ฿5,400.00 2021-05-10 2021-05-27
39    SENA  ฿0.1850   60000  ฿11,100.00  ฿10,043.96 2021-05-11 2021-05-21
40     CPF  ฿0.6000   10000   ฿6,000.00   ฿5,400.00 2021-05-17 2021-05-28

In [50]:
df.xd_date = df.xd_date + timedelta(days=365)
df.pay_date = df.pay_date + timedelta(days=365)
df.xd_date,df.pay_date

(0    2022-02-11
 1    2022-02-19
 2    2022-02-23
 3    2022-02-24
 4    2022-02-24
 5    2022-02-25
 6    2022-02-25
 7    2022-02-25
 8    2022-03-01
 9    2022-03-01
 10   2022-03-01
 11   2022-03-01
 12   2022-03-02
 13   2022-03-04
 14   2022-03-08
 15   2022-03-08
 16   2022-03-09
 17   2022-03-09
 18   2022-03-11
 19   2022-03-12
 20   2022-03-12
 21   2022-03-15
 22   2022-03-15
 23   2022-04-04
 24   2022-04-05
 25   2022-04-16
 26   2022-04-21
 27   2022-04-21
 28   2022-04-22
 29   2022-04-28
 30   2022-04-29
 31   2022-04-30
 32   2022-04-30
 33   2022-05-06
 34   2022-05-06
 35   2022-05-06
 36   2022-05-07
 37   2022-05-07
 38   2022-05-10
 39   2022-05-11
 40   2022-05-17
 Name: xd_date, dtype: datetime64[ns],
 0    2022-04-20
 1    2022-04-20
 2    2022-03-12
 3    2022-03-15
 4    2022-05-04
 5    2022-03-10
 6    2022-03-11
 7    2022-04-23
 8    2022-04-23
 9    2022-03-17
 10   2022-03-30
 11   2022-03-17
 12   2022-04-23
 13   2022-03-22
 14   2022-04-21
 15   2022-05-25
 16   2022-04-27
 17   2022-04-29
 18   2022-05-19
 19   2022-05-07
 20   2022-05-14
 21   2022-04-28
 22   2022-05-20
 23   2022-04-30
 24   2022-04-27
 25   2022-04-30
 26   2022-05-07
 27   2022-05-07
 28   2022-05-07
 29   2022-05-17
 30   2022-05-17
 31   2022-05-20
 32   2022-05-21
 33   2022-05-24
 34   2022-05-20
 35   2022-05-21
 36   2022-05-18
 37   2022-05-25
 38   2022-05-27
 39   2022-05-21
 40   2022-05-28
 Name: pay_date, dtype: datetime64[ns])

In [51]:
df.to_sql('div_update', engine1, if_exists='replace')

In [52]:
sql = '''
SELECT *
FROM div_update'''
df_upd = pd.read_sql(sql, const)
df_upd

,index,name,qtr,shares,dividend,net,xd_date,pay_date
0,0,DTAC,?2.1200,9000,"?19,080.00","?17,172.00",2022-02-11,2022-04-20
1,1,ADVANC,?3.6800,600,"?2,208.00","?1,987.20",2022-02-19,2022-04-20
2,2,DIF,?0.2610,80000,"?20,880.00","?20,880.00",2022-02-23,2022-03-12
3,3,JASIF,?0.2500,130000,"?32,500.00","?32,500.00",2022-02-24,2022-03-15
4,4,SCCC,?9.0000,600,"?5,400.00","?4,860.00",2022-02-24,2022-05-04
5,5,GVREIT,?0.2037,18000,"?3,666.60","?3,299.94",2022-02-25,2022-03-10
6,6,MC,?0.3500,10000,"?3,500.00","?3,150.00",2022-02-25,2022-03-11
7,7,PTTGC,?1.0000,2000,"?2,000.00","?1,800.00",2022-02-25,2022-04-23
8,8,CPTGF,?0.1800,10000,"?1,800.00","?1,620.00",2022-03-01,2022-04-23
9,9,EGATIF,?0.2000,10000,"?2,000.00","?2,000.00",2022-03-01,2022-03-17
10,10,HREIT,?0.0860,30000,"?2,580.00","?2,322.00",2022-03-01,2022-03-30
11,11,TTLPF,?0.4300,11100,"?4,773.00","?4,295.70",2022-03-01,2022-03-17
12,12,RATCH,?1.2500,6000,"?7,500.00","?6,750.00",2022-03-02,2022-04-23
13,13,WHART,?0.1195,10000,"?1,195.00","?1,075.50",2022-03-04,2022-03-22
14,14,TU,?0.4000,21000,"?8,400.00","?7,770.00",2022-03-08,2022-04-21
15,15,UTP,?0.3900,6000,"?2,340.00","?2,106.00",2022-03-08,2022-05-25
16,16,EGCO,?3.5000,900,"?3,150.00","?2,835.00",2022-03-09,2022-04-27
17,17,FSMART,?0.3000,18000,"?5,400.00","?4,860.00",2022-03-09,2022-04-29
18,18,TIP,?1.3000,3000,"?3,900.00","?3,510.00",2022-03-11,2022-05-19
19,19,TPIPP,?0.1500,60000,"?9,000.00","?9,000.00",2022-03-12,2022-05-07
20,20,TVO,?0.8000,6000,"?4,800.00","?4,320.00",2022-03-12,2022-05-14
21,21,MCS,?0.6000,75000,"?45,000.00","?43,050.00",2022-03-15,2022-04-28
22,22,PDG,?0.2200,25000,"?5,500.00","?4,950.00",2022-03-15,2022-05-20
23,23,SMPC,?0.4300,20000,"?8,600.00","?7,740.00",2022-04-04,2022-04-30
24,24,DCC,?0.0440,40000,"?1,760.00","?1,584.00",2022-04-05,2022-04-27
25,25,GC,?0.4000,15000,"?6,000.00","?5,400.00",2022-04-16,2022-04-30
26,26,BGC,?0.1200,10000,"?1,200.00","?1,200.00",2022-04-21,2022-05-07
27,27,MBAX,?0.5600,12000,"?6,720.00","?6,048.00",2022-04-21,2022-05-07
28,28,AMATA,?0.2000,12000,"?2,400.00","?2,160.00",2022-04-22,2022-05-07
29,29,TISCO,?6.3000,2000,"?12,600.00","?11,340.00",2022-04-28,2022-05-17
30,30,ASIAN,?0.5500,10000,"?5,500.00","?4,450.00",2022-04-29,2022-05-17
31,31,PRM,?0.1800,33000,"?5,940.00","?5,398.80",2022-04-30,2022-05-20
32,32,TCAP,?1.8000,3000,"?5,400.00","?4,860.00",2022-04-30,2022-05-21
33,33,GUNKUL,?0.1820,30000,"?5,460.00","?4,914.00",2022-05-06,2022-05-24
34,34,IVL,?0.1750,10000,"?1,750.00","?1,575.00",2022-05-06,2022-05-20
35,35,LH,?0.3000,42000,"?12,600.00","?11,340.00",2022-05-06,2022-05-21
36,36,ORI,?0.3900,50000,"?19,500.00","?17,550.00",2022-05-07,2022-05-18
37,37,ROJNA,?0.2000,20000,"?4,000.00","?3,600.00",2022-05-07,2022-05-25
38,38,NOBLE,?0.5000,12000,"?6,000.00","?5,400.00",2022-05-10,2022-05-27
39,39,SENA,?0.1850,60000,"?11,100.00","?10,043.96",2022-05-11,2022-05-21
40,40,CPF,?0.6000,10000,"?6,000.00","?5,400.00",2022-05-17,2022-05-28

In [54]:
sqlUpd = '''
UPDATE dividend D
SET XDATE = 
(SELECT xd_date FROM div_update U
WHERE D.NAME = U.name)'''
print(sqlUpd)

UPDATE dividend D
SET XDATE =
(SELECT xd_date FROM div_update U
WHERE D.NAME = U.name)

In [55]:
rp = const.execute(sqlUpd)
rp.rowcount

79

In [65]:
sql = '''
SELECT * FROM dividend WHERE XDATE IS NULL
'''
df_dividend = pd.read_sql(sql, const)
df_dividend

,NAME,Q4,Q3,Q2,Q1,DIVIDEND,PRICE,PERCENT,SHARES,XDATE,PAIDDATE,KIND,ACTUAL
0,QH,0.0800,0.0000,0.0300,0.0000,0.1100,0.0,0.0,0.0,None,2021-09-07,None,0
1,TQM,1.1500,0.0000,1.4500,0.0000,2.6000,0.0,0.0,0.0,None,2021-09-09,,0
2,HTC,1.1200,0.0000,0.8300,0.0000,1.9500,0.0,0.0,0.0,None,2021-09-23,,0
3,SCC,8.5000,0.0000,8.5000,0.0000,17.0000,0.0,0.0,600.0,None,2021-08-27,,0
4,IP,0.1850,0.0000,0.0000,0.0000,0.1850,0.0,0.0,7500.0,None,2022-04-27,,0
5,NER,0.1500,0.0000,0.0700,0.0000,0.2200,0.0,0.0,36000.0,None,2021-09-06,,0
6,AIMIRT,0.2175,0.2207,0.2205,0.2200,0.8787,0.0,0.0,0.0,None,2021-12-13,,0
7,PTT,0.8200,0.0000,1.2000,0.0000,2.0200,0.0,0.0,9000.0,None,2021-10-15,None,0
8,TOP,0.7000,0.0000,0.6000,0.0000,1.3000,0.0,0.0,3000.0,None,2022-04-26,,0
9,TTW,0.3000,0.0000,0.3000,0.0000,0.6000,0.0,0.0,0.0,None,2021-09-23,None,0
10,TCCC,1.8000,0.0000,0.0000,0.0000,1.8000,0.0,0.0,0.0,None,2021-04-22,,0
11,DOHOME,0.1000,0.0000,0.0000,0.0000,0.1000,0.0,0.0,8000.0,None,2021-05-21,,0
12,TMT,0.5000,0.0000,0.6000,0.0000,1.1000,0.0,0.0,27000.0,None,2021-09-10,,0
13,THANI,0.1700,0.0000,0.1600,0.0000,0.3300,0.0,0.0,0.0,None,2021-04-27,None,0
14,SUPEREIF,0.1534,0.1684,0.2520,0.2670,0.8408,0.0,0.0,0.0,None,2021-12-14,,0
15,BCP,0.4000,0.0000,1.0000,0.0000,1.4000,0.0,0.0,0.0,None,2021-09-21,,0
16,TFFIF,0.1012,0.1210,0.0685,0.0873,0.3780,0.0,0.0,0.0,None,2021-12-17,,0
17,SAT,0.4800,0.0000,0.4000,0.0000,0.8800,0.0,0.0,7500.0,None,2021-09-07,,0
18,STGT,2.0000,1.2500,1.2500,0.0000,4.5000,0.0,0.0,0.0,None,2021-12-07,,0
19,AP,0.4500,0.0000,0.0000,0.0000,0.4500,0.0,0.0,0.0,None,2021-05-27,,0
20,STA,1.7500,1.2500,1.2500,1.0000,5.2500,0.0,0.0,20000.0,None,2021-12-08,,0
21,PSH,0.6500,0.0000,0.3100,0.0000,0.9600,0.0,0.0,0.0,None,2021-05-21,None,0
22,ASK,1.7000,0.0000,0.0000,0.0000,1.7000,0.0,0.0,0.0,None,2021-05-06,,0
23,CHG,0.0300,0.0000,0.0300,0.0000,0.0600,0.0,0.0,0.0,None,2021-09-10,,0
24,SPALI,0.5000,0.0000,0.5000,0.0000,1.0000,0.0,0.0,0.0,None,2021-05-14,,0
25,DRT,0.2200,0.0000,0.2000,0.0000,0.4200,0.0,0.0,0.0,None,2021-05-14,None,0
26,KCE,0.4000,0.0000,0.6000,0.0000,1.0000,0.0,0.0,4000.0,None,2021-09-08,,0
27,SYNEX,0.4000,0.0000,0.1800,0.0000,0.5800,0.0,0.0,0.0,None,2021-09-03,,0
28,SIS,1.0000,0.0000,0.0000,0.0000,1.0000,0.0,0.0,1500.0,None,2021-05-14,,0
29,SC,0.1800,0.0000,0.0000,0.0000,0.1800,0.0,0.0,0.0,None,2021-05-20,,0
30,KKP,2.2500,0.0000,0.7500,0.0000,3.0000,0.0,0.0,0.0,None,2021-09-23,,0
31,TIF1,0.1800,0.1500,0.1470,0.1380,0.6150,0.0,0.0,0.0,None,2021-12-17,,0
32,MST,0.5000,0.0000,0.1000,0.0000,0.6000,0.0,0.0,0.0,None,2021-04-28,,0
33,BCH,0.1300,0.0000,0.2000,0.0000,0.3300,0.0,0.0,15000.0,None,2021-09-15,,0
34,JMT,0.4100,0.0000,0.4000,0.0000,0.8100,0.0,0.0,0.0,None,2021-09-06,,0
35,EPG,0.0000,0.1400,0.0000,0.0900,0.2300,0.0,0.0,14000.0,None,2021-12-08,,0
36,VNT,0.9000,0.0000,0.0000,0.0000,0.9000,0.0,0.0,0.0,None,2021-05-21,,0
37,WIIK,0.0900,0.0000,0.1000,0.0000,0.1900,0.0,0.0,0.0,None,2021-05-21,,0
38,LPF,0.2000,0.1894,0.1793,0.1878,0.7565,0.0,0.0,0.0,None,2021-11-12,,0
39,BKI,6.0000,3.0000,3.5000,3.5000,16.0000,0.0,0.0,0.0,None,2021-12-09,,0
40,TOA,0.2600,0.0000,0.3100,0.0000,0.5700,0.0,0.0,0.0,None,2021-09-10,,0
41,TIPH,1.3000,0.0000,0.5000,0.5000,2.3000,0.0,0.0,0.0,None,2021-09-22,,0
42,CPNCG,0.2515,0.2400,0.2450,0.2515,0.9880,0.0,0.0,0.0,None,2021-12-03,,0
43,JMART,0.2400,0.0000,0.4000,0.1500,0.7900,0.0,0.0,0.0,None,2021-09-08,,0
44,CKP,0.0350,0.0000,0.0000,0.0000,0.0350,0.0,0.0,0.0,None,2022-05-20,,0
45,BGRIM,0.3000,0.0000,0.1500,0.0000,0.4500,0.0,0.0,9000.0,None,2021-05-11,,0
46,KBANK,2.5000,0.0000,0.5000,0.0000,3.0000,0.0,0.0,2400.0,None,2022-05-07,,0
47,RJH,0.2000,1.1000,0.4000,0.0000,1.7000,0.0,0.0,4500.0,None,2021-12-07,,0
48,RCL,0.5000,1.5000,1.5000,0.0000,3.5000,0.0,0.0,4500.0,None,2021-12-03,,0

In [66]:
sqlUpd = '''
UPDATE dividend
SET XDATE = PAIDDATE WHERE XDATE IS NULL
'''
rp = const.execute(sqlUpd)
rp.rowcount

49

In [67]:
sql = '''
SELECT * FROM dividend WHERE XDATE = PAIDDATE
'''
df_dividend = pd.read_sql(sql, const)
df_dividend

,NAME,Q4,Q3,Q2,Q1,DIVIDEND,PRICE,PERCENT,SHARES,XDATE,PAIDDATE,KIND,ACTUAL
0,QH,0.0800,0.0000,0.0300,0.0000,0.1100,0.0,0.0,0.0,2021-09-07,2021-09-07,None,0
1,TQM,1.1500,0.0000,1.4500,0.0000,2.6000,0.0,0.0,0.0,2021-09-09,2021-09-09,,0
2,HTC,1.1200,0.0000,0.8300,0.0000,1.9500,0.0,0.0,0.0,2021-09-23,2021-09-23,,0
3,SCC,8.5000,0.0000,8.5000,0.0000,17.0000,0.0,0.0,600.0,2021-08-27,2021-08-27,,0
4,IP,0.1850,0.0000,0.0000,0.0000,0.1850,0.0,0.0,7500.0,2022-04-27,2022-04-27,,0
5,NER,0.1500,0.0000,0.0700,0.0000,0.2200,0.0,0.0,36000.0,2021-09-06,2021-09-06,,0
6,AIMIRT,0.2175,0.2207,0.2205,0.2200,0.8787,0.0,0.0,0.0,2021-12-13,2021-12-13,,0
7,PTT,0.8200,0.0000,1.2000,0.0000,2.0200,0.0,0.0,9000.0,2021-10-15,2021-10-15,None,0
8,TOP,0.7000,0.0000,0.6000,0.0000,1.3000,0.0,0.0,3000.0,2022-04-26,2022-04-26,,0
9,TTW,0.3000,0.0000,0.3000,0.0000,0.6000,0.0,0.0,0.0,2021-09-23,2021-09-23,None,0
10,TCCC,1.8000,0.0000,0.0000,0.0000,1.8000,0.0,0.0,0.0,2021-04-22,2021-04-22,,0
11,DOHOME,0.1000,0.0000,0.0000,0.0000,0.1000,0.0,0.0,8000.0,2021-05-21,2021-05-21,,0
12,TMT,0.5000,0.0000,0.6000,0.0000,1.1000,0.0,0.0,27000.0,2021-09-10,2021-09-10,,0
13,THANI,0.1700,0.0000,0.1600,0.0000,0.3300,0.0,0.0,0.0,2021-04-27,2021-04-27,None,0
14,SUPEREIF,0.1534,0.1684,0.2520,0.2670,0.8408,0.0,0.0,0.0,2021-12-14,2021-12-14,,0
15,BCP,0.4000,0.0000,1.0000,0.0000,1.4000,0.0,0.0,0.0,2021-09-21,2021-09-21,,0
16,TFFIF,0.1012,0.1210,0.0685,0.0873,0.3780,0.0,0.0,0.0,2021-12-17,2021-12-17,,0
17,SAT,0.4800,0.0000,0.4000,0.0000,0.8800,0.0,0.0,7500.0,2021-09-07,2021-09-07,,0
18,STGT,2.0000,1.2500,1.2500,0.0000,4.5000,0.0,0.0,0.0,2021-12-07,2021-12-07,,0
19,AP,0.4500,0.0000,0.0000,0.0000,0.4500,0.0,0.0,0.0,2021-05-27,2021-05-27,,0
20,STA,1.7500,1.2500,1.2500,1.0000,5.2500,0.0,0.0,20000.0,2021-12-08,2021-12-08,,0
21,PSH,0.6500,0.0000,0.3100,0.0000,0.9600,0.0,0.0,0.0,2021-05-21,2021-05-21,None,0
22,ASK,1.7000,0.0000,0.0000,0.0000,1.7000,0.0,0.0,0.0,2021-05-06,2021-05-06,,0
23,CHG,0.0300,0.0000,0.0300,0.0000,0.0600,0.0,0.0,0.0,2021-09-10,2021-09-10,,0
24,SPALI,0.5000,0.0000,0.5000,0.0000,1.0000,0.0,0.0,0.0,2021-05-14,2021-05-14,,0
25,DRT,0.2200,0.0000,0.2000,0.0000,0.4200,0.0,0.0,0.0,2021-05-14,2021-05-14,None,0
26,KCE,0.4000,0.0000,0.6000,0.0000,1.0000,0.0,0.0,4000.0,2021-09-08,2021-09-08,,0
27,SYNEX,0.4000,0.0000,0.1800,0.0000,0.5800,0.0,0.0,0.0,2021-09-03,2021-09-03,,0
28,SIS,1.0000,0.0000,0.0000,0.0000,1.0000,0.0,0.0,1500.0,2021-05-14,2021-05-14,,0
29,SC,0.1800,0.0000,0.0000,0.0000,0.1800,0.0,0.0,0.0,2021-05-20,2021-05-20,,0
30,KKP,2.2500,0.0000,0.7500,0.0000,3.0000,0.0,0.0,0.0,2021-09-23,2021-09-23,,0
31,TIF1,0.1800,0.1500,0.1470,0.1380,0.6150,0.0,0.0,0.0,2021-12-17,2021-12-17,,0
32,MST,0.5000,0.0000,0.1000,0.0000,0.6000,0.0,0.0,0.0,2021-04-28,2021-04-28,,0
33,BCH,0.1300,0.0000,0.2000,0.0000,0.3300,0.0,0.0,15000.0,2021-09-15,2021-09-15,,0
34,JMT,0.4100,0.0000,0.4000,0.0000,0.8100,0.0,0.0,0.0,2021-09-06,2021-09-06,,0
35,EPG,0.0000,0.1400,0.0000,0.0900,0.2300,0.0,0.0,14000.0,2021-12-08,2021-12-08,,0
36,VNT,0.9000,0.0000,0.0000,0.0000,0.9000,0.0,0.0,0.0,2021-05-21,2021-05-21,,0
37,WIIK,0.0900,0.0000,0.1000,0.0000,0.1900,0.0,0.0,0.0,2021-05-21,2021-05-21,,0
38,LPF,0.2000,0.1894,0.1793,0.1878,0.7565,0.0,0.0,0.0,2021-11-12,2021-11-12,,0
39,BKI,6.0000,3.0000,3.5000,3.5000,16.0000,0.0,0.0,0.0,2021-12-09,2021-12-09,,0
40,TOA,0.2600,0.0000,0.3100,0.0000,0.5700,0.0,0.0,0.0,2021-09-10,2021-09-10,,0
41,TIPH,1.3000,0.0000,0.5000,0.5000,2.3000,0.0,0.0,0.0,2021-09-22,2021-09-22,,0
42,CPNCG,0.2515,0.2400,0.2450,0.2515,0.9880,0.0,0.0,0.0,2021-12-03,2021-12-03,,0
43,JMART,0.2400,0.0000,0.4000,0.1500,0.7900,0.0,0.0,0.0,2021-09-08,2021-09-08,,0
44,CKP,0.0350,0.0000,0.0000,0.0000,0.0350,0.0,0.0,0.0,2022-05-20,2022-05-20,,0
45,BGRIM,0.3000,0.0000,0.1500,0.0000,0.4500,0.0,0.0,9000.0,2021-05-11,2021-05-11,,0
46,KBANK,2.5000,0.0000,0.5000,0.0000,3.0000,0.0,0.0,2400.0,2022-05-07,2022-05-07,,0
47,RJH,0.2000,1.1000,0.4000,0.0000,1.7000,0.0,0.0,4500.0,2021-12-07,2021-12-07,,0
48,RCL,0.5000,1.5000,1.5000,0.0000,3.5000,0.0,0.0,4500.0,2021-12-03,2021-12-03,,0

In [68]:
sql = '''
SELECT * FROM dividend WHERE XDATE = PAIDDATE
AND SHARES > 0
'''
df_dividend = pd.read_sql(sql, const)
df_dividend

,NAME,Q4,Q3,Q2,Q1,DIVIDEND,PRICE,PERCENT,SHARES,XDATE,PAIDDATE,KIND,ACTUAL
0,SCC,8.500,0.00,8.50,0.00,17.000,0.0,0.0,600.0,2021-08-27,2021-08-27,,0
1,IP,0.185,0.00,0.00,0.00,0.185,0.0,0.0,7500.0,2022-04-27,2022-04-27,,0
2,NER,0.150,0.00,0.07,0.00,0.220,0.0,0.0,36000.0,2021-09-06,2021-09-06,,0
3,PTT,0.820,0.00,1.20,0.00,2.020,0.0,0.0,9000.0,2021-10-15,2021-10-15,None,0
4,TOP,0.700,0.00,0.60,0.00,1.300,0.0,0.0,3000.0,2022-04-26,2022-04-26,,0
5,DOHOME,0.100,0.00,0.00,0.00,0.100,0.0,0.0,8000.0,2021-05-21,2021-05-21,,0
6,TMT,0.500,0.00,0.60,0.00,1.100,0.0,0.0,27000.0,2021-09-10,2021-09-10,,0
7,SAT,0.480,0.00,0.40,0.00,0.880,0.0,0.0,7500.0,2021-09-07,2021-09-07,,0
8,STA,1.750,1.25,1.25,1.00,5.250,0.0,0.0,20000.0,2021-12-08,2021-12-08,,0
9,KCE,0.400,0.00,0.60,0.00,1.000,0.0,0.0,4000.0,2021-09-08,2021-09-08,,0
10,SIS,1.000,0.00,0.00,0.00,1.000,0.0,0.0,1500.0,2021-05-14,2021-05-14,,0
11,BCH,0.130,0.00,0.20,0.00,0.330,0.0,0.0,15000.0,2021-09-15,2021-09-15,,0
12,EPG,0.000,0.14,0.00,0.09,0.230,0.0,0.0,14000.0,2021-12-08,2021-12-08,,0
13,BGRIM,0.300,0.00,0.15,0.00,0.450,0.0,0.0,9000.0,2021-05-11,2021-05-11,,0
14,KBANK,2.500,0.00,0.50,0.00,3.000,0.0,0.0,2400.0,2022-05-07,2022-05-07,,0
15,RJH,0.200,1.10,0.40,0.00,1.700,0.0,0.0,4500.0,2021-12-07,2021-12-07,,0
16,RCL,0.500,1.50,1.50,0.00,3.500,0.0,0.0,4500.0,2021-12-03,2021-12-03,,0