### Re-run the whole notebook

In [1]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
year = 2021
quarter = 3

In [2]:
sql = """
SELECT name,year,quarter,q_amt 
FROM epss 
WHERE (year = %s AND quarter <= %s) 
OR (year = %s-1 AND quarter >= %s+1)
ORDER BY year DESC, quarter DESC
"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT name,year,quarter,q_amt
FROM epss
WHERE (year = 2021 AND quarter <= 3)
OR (year = 2021-1 AND quarter >= 3+1)
ORDER BY year DESC, quarter DESC

In [3]:
dfc = pd.read_sql(sql, conlt)
dfc["Counter"] = 1
dfc_grp = dfc.groupby(["name"], as_index=False).sum()
dfc_grp = dfc_grp[dfc_grp["Counter"] == 4]
dfc_grp.shape

(319, 5)

In [4]:
sql = """
SELECT name,year,quarter,q_amt 
FROM epss 
WHERE (year = %s AND quarter <= %s-1) 
OR (year = %s-1 AND quarter >= %s) 
ORDER BY year DESC, quarter DESC"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT name,year,quarter,q_amt
FROM epss
WHERE (year = 2021 AND quarter <= 3-1)
OR (year = 2021-1 AND quarter >= 3)
ORDER BY year DESC, quarter DESC

In [5]:
dfp = pd.read_sql(sql, conlt)
dfp["Counter"] = 1
dfp_grp = dfp.groupby(["name"], as_index=False).sum()
dfp_grp = dfp_grp[dfp_grp["Counter"] == 4]
dfp_grp.shape

(334, 5)

In [6]:
dfm = pd.merge(dfc_grp, dfp_grp, on="name", suffixes=(["_c", "_p"]), how="inner")
dfm["inc_profit"] = dfm["q_amt_c"] - dfm["q_amt_p"]
dfm["Pct"] = dfm["inc_profit"] / abs(dfm["q_amt_p"]) * 100
dfm["year"] = year
dfm["quarter"] = "Q" + str(quarter)
df_pct = dfm[["name", "year", "quarter", "q_amt_c", "q_amt_p", "inc_profit", "Pct"]]
df_pct.shape

(319, 7)

In [7]:
sql = '''
DELETE FROM qt_profits 
WHERE year = %s AND quarter = "Q%s"'''
sql = sql % (year, quarter)
rp = conlt.execute(sql)
rp.rowcount

318

In [8]:
sql = "SELECT name, id FROM tickers"
tickers = pd.read_sql(sql, conlt)
tickers.shape

(402, 2)

In [9]:
df_ins = pd.merge(df_pct, tickers, on="name", how="inner")
df_ins.shape

(319, 8)

In [10]:
rcds = df_ins.values.tolist()
len(rcds)

319

In [11]:
for rcd in rcds:
    print(rcd)

['2S', 2021, 'Q3', 788297, 725410, 62887, 8.66916640244827, 727]
['AAV', 2021, 'Q3', -6769190, -6507746, -261444, -4.0174278467537, 732]
['ACE', 2021, 'Q3', 1392091, 1391075, 1016, 0.07303703969951296, 698]
['ADVANC', 2021, 'Q3', 27223149, 27361758, -138609, -0.5065792921639026, 6]
['AEONTS', 2021, 'Q3', 3826113, 4020604, -194491, -4.837357770126081, 7]
['AH', 2021, 'Q3', 1041977, 1109197, -67220, -6.060239975405631, 9]
['AIE', 2021, 'Q3', 522478, 495054, 27424, 5.53959770045288, 720]
['AIMIRT', 2021, 'Q3', 437639, 425165, 12474, 2.933919772323686, 669]
['AIT', 2021, 'Q3', 522365, 542406, -20041, -3.6948337592135783, 11]
['AJ', 2021, 'Q3', 389174, 591137, -201963, -34.16517660034814, 12]
['AKR', 2021, 'Q3', 123963, 131696, -7733, -5.87185639654963, 14]
['ALUCON', 2021, 'Q3', 725936, 666612, 59324, 8.899329745039093, 17]
['AMANAH', 2021, 'Q3', 307691, 312616, -4925, -1.5754152058755788, 19]
['AMARIN', 2021, 'Q3', 367215, 419049, -51834, -12.369436509811502, 20]
['AMATA', 2021, 'Q3', 1058096, 1098346, -40250, -3.6646011366181517, 21]
['AMC', 2021, 'Q3', 809057, 665184, 143873, 21.629053013902922, 22]
['ANAN', 2021, 'Q3', -311727, 232533, -544260, -234.05710157268, 23]
['AOT', 2021, 'Q3', -14892318, -13747749, -1144569, -8.325501142041508, 24]
['AP', 2021, 'Q3', 4491151, 4910383, -419232, -8.537663966334193, 25]
['APCS', 2021, 'Q3', 255805, 233502, 22303, 9.551524183947032, 27]
['APURE', 2021, 'Q3', 354554, 335304, 19250, 5.741058860019564, 28]
['ARROW', 2021, 'Q3', 157109, 173530, -16421, -9.462917074857373, 31]
['ASIAN', 2021, 'Q3', 989973, 921153, 68820, 7.4710715809425805, 36]
['ASK', 2021, 'Q3', 1080308, 997509, 82799, 8.300576736650997, 38]
['ASP', 2021, 'Q3', 907856, 818663, 89193, 10.894959220094227, 40]
['AWC', 2021, 'Q3', -597662, -1905093, 1307431, 68.62819820344728, 699]
['AYUD', 2021, 'Q3', 1332945, 1290589, 42356, 3.2819123671439936, 44]
['BA', 2021, 'Q3', -8809152, -3401356, -5407796, -158.98941480985818, 45]
['BAM', 2021, 'Q3', 2321436, 2043406, 278030, 13.60620454280745, 709]
['BANPU', 2021, 'Q3', 5897490, 1875967, 4021523, 214.37066856719758, 47]
['BAY', 2021, 'Q3', 30793995, 30547119, 246876, 0.8081809613535077, 49]
['BBL', 2021, 'Q3', 22586660, 19694952, 2891708, 14.682483105315514, 50]
['BCH', 2021, 'Q3', 4644042, 2161170, 2482872, 114.8855481058871, 51]
['BCP', 2021, 'Q3', 6119569, 3652466, 2467103, 67.54622767193452, 52]
['BCPG', 2021, 'Q3', 2083827, 2072213, 11614, 0.5604636202938598, 53]
['BDMS', 2021, 'Q3', 7687881, 6979197, 708684, 10.154234075925926, 54]
['BEAUTY', 2021, 'Q3', -53418, -54152, 734, 1.3554439355887131, 55]
['BEC', 2021, 'Q3', 733898, 651178, 82720, 12.703131862562925, 56]
['BEM', 2021, 'Q3', 1183772, 1896988, -713216, -37.59728580254593, 57]
['BEYOND', 2021, 'Q3', 290578, 101562, 189016, 186.10897776727515, 348]
['BFIT', 2021, 'Q3', 924632, 1137533, -212901, -18.716028458075503, 58]
['BGC', 2021, 'Q3', 550097, 580230, -30133, -5.193285421298451, 677]
['BGRIM', 2021, 'Q3', 2656572, 2709864, -53292, -1.9665931574425877, 59]
['BH', 2021, 'Q3', 776568, 702109, 74459, 10.605048503864785, 61]
['BJC', 2021, 'Q3', 3555645, 4250863, -695218, -16.35474961201996, 65]
['BKI', 2021, 'Q3', 1167613, 2814491, -1646878, -58.51423934203378, 68]
['BLA', 2021, 'Q3', 3085271, 2488156, 597115, 23.998294319166483, 70]
['BPP', 2021, 'Q3', 3957525, 4206463, -248938, -5.917988580905146, 74]
['BRR', 2021, 'Q3', 60421, 240601, -180180, -74.88746929563884, 78]
['BSBM', 2021, 'Q3', 85267, 98462, -13195, -13.401109057301294, 79]
['CBG', 2021, 'Q3', 3141225, 3509632, -368407, -10.497026468871951, 87]
['CCET', 2021, 'Q3', 526537, 212727, 313810, 147.51771049279122, 88]
['CENTEL', 2021, 'Q3', -3252627, -3346731, 94104, 2.8118184580714733, 92]
['CGH', 2021, 'Q3', 654014, 239834, 414180, 172.69444699250315, 95]
['CHAYO', 2021, 'Q3', 206771, 167910, 38861, 23.14394616163421, 671]
['CHG', 2021, 'Q3', 2644996, 1363171, 1281825, 94.03259018861169, 98]
['CIMBT', 2021, 'Q3', 1531200, 859475, 671725, 78.15526920503795, 104]
['CK', 2021, 'Q3', 688655, 1187899, -499244, -42.02747876713424, 106]
['CKP', 2021, 'Q3', 2064271, 1660663, 403608, 24.30402796955192, 107]
['COM7', 2021, 'Q3', 2279167, 2080948, 198219, 9.525418222848431, 114]
['COTTO', 2021, 'Q3', 609378, 618161, -8783, -1.4208272602121454, 710]
['CPALL', 2021, 'Q3', 9854339, 12359033, -2504694, -20.266100106699287, 116]
['CPF', 2021, 'Q3', 12716970, 25565705, -12848735, -50.25769874134119, 117]
['CPI', 2021, 'Q3', 318049, 349849, -31800, -9.089635814308458, 119]
['CPN', 2021, 'Q3', 7349847, 9601203, -2251356, -23.448686586462134, 121]
['CPNCG', 2021, 'Q3', 402489, 429144, -26655, -6.21120183434931, 122]
['CPNREIT', 2021, 'Q3', -329271, 22899, -352170, -1537.9274204113717, 647]
['CPTGF', 2021, 'Q3', 681239, 679493, 1746, 0.2569562894687657, 690]
['CRC', 2021, 'Q3', 3227788, 1823748, 1404040, 76.98651348760903, 708]
['CSP', 2021, 'Q3', 438381, 335870, 102511, 30.521034924226637, 129]
['CSS', 2021, 'Q3', 85427, 83260, 2167, 2.6026903675234205, 131]
['CWT', 2021, 'Q3', 208170, 182772, 25398, 13.896001575733703, 134]
['DCC', 2021, 'Q3', 1674358, 1720989, -46631, -2.709546661832237, 135]
['DCON', 2021, 'Q3', 111660, 111388, 272, 0.24419147484468703, 136]
['DDD', 2021, 'Q3', 180492, 239572, -59080, -24.660644816589585, 665]
['DELTA', 2021, 'Q3', 6184967, 7635796, -1450829, -19.00036355083347, 138]
['DEMCO', 2021, 'Q3', 91260, 70575, 20685, 29.309245483528162, 139]
['DIF', 2021, 'Q3', 13757407, 13671122, 86285, 0.6311479043197771, 140]
['DOHOME', 2021, 'Q3', 1700256, 1547450, 152806, 9.874697082296683, 701]
['DRT', 2021, 'Q3', 588536, 581128, 7408, 1.2747621866439063, 143]
['DTAC', 2021, 'Q3', 3465917, 4069550, -603633, -14.832917644457003, 144]
['DUSIT', 2021, 'Q3', -737049, -777530, 40481, 5.2063585970959325, 145]
['EA', 2021, 'Q3', 5702847, 5205589, 497258, 9.552386867269007, 148]
['EASTW', 2021, 'Q3', 1036000, 947929, 88071, 9.29088570979472, 151]
['ECL', 2021, 'Q3', 148542, 150189, -1647, -1.0966182609911512, 153]
['EGATIF', 2021, 'Q3', 639121, 462260, 176861, 38.2600700904253, 156]
['EGCO', 2021, 'Q3', 4973588, 6167223, -1193635, -19.354497153743264, 157]
['EKH', 2021, 'Q3', 300437, 160518, 139919, 87.16717128297138, 159]
['EMC', 2021, 'Q3', 63809, 62589, 1220, 1.9492243045902635, 691]
['ESSO', 2021, 'Q3', 4126097, 4546503, -420406, -9.24679913331191, 165]
['FORTH', 2021, 'Q3', 725253, 704983, 20270, 2.875246637152953, 176]
['FPI', 2021, 'Q3', 215039, 174288, 40751, 23.38141466997154, 177]
['FSMART', 2021, 'Q3', 429577, 457502, -27925, -6.103798453340095, 178]
['FSS', 2021, 'Q3', 260306, 214201, 46105, 21.524175890868857, 179]
['GBX', 2021, 'Q3', 129832, 109579, 20253, 18.48255596419022, 182]
['GC', 2021, 'Q3', 193488, 195021, -1533, -0.7860691925484948, 183]
['GFPT', 2021, 'Q3', 617194, 1046548, -429354, -41.02573412781831, 187]
['GGC', 2021, 'Q3', 983347, 839101, 144246, 17.1905408288156, 188]
['GLAND', 2021, 'Q3', 511497, 544672, -33175, -6.090821632101521, 192]
['GLOBAL', 2021, 'Q3', 2974789, 2771160, 203629, 7.3481502331153745, 193]
['GPI', 2021, 'Q3', 41765, 263622, -221857, -84.15724029102275, 652]
['GPSC', 2021, 'Q3', 7608216, 8307852, -699636, -8.421382566757329, 197]
['GRAMMY', 2021, 'Q3', 136116, 159284, -23168, -14.545089274503404, 198]
['GULF', 2021, 'Q3', 6471046, 5853218, 617828, 10.555356045170367, 653]
['GUNKUL', 2021, 'Q3', 3414243, 3826318, -412075, -10.769491715011664, 202]
['GVREIT', 2021, 'Q3', 823986, 788226, 35760, 4.5367699111676085, 654]
['HANA', 2021, 'Q3', 2303427, 2059694, 243733, 11.833456814458847, 205]
['HFT', 2021, 'Q3', 493119, 539566, -46447, -8.608214750373449, 207]
['HMPRO', 2021, 'Q3', 5210457, 5740561, -530104, -9.234358802214626, 208]
['HREIT', 2021, 'Q3', 786155, 761288, 24867, 3.266437931505554, 211]
['HTC', 2021, 'Q3', 545441, 588270, -42829, -7.280500450473422, 212]
['HTECH', 2021, 'Q3', 120176, 117111, 3065, 2.617175158610207, 213]
['HUMAN', 2021, 'Q3', 172008, 173608, -1600, -0.9216165153679554, 655]
['ICC', 2021, 'Q3', -1631, 55386, -57017, -102.94478749142382, 215]
['ICHI', 2021, 'Q3', 498194, 492876, 5318, 1.0789732103003595, 216]
['IFS', 2021, 'Q3', 143451, 122593, 20858, 17.014022007781847, 219]
['IHL', 2021, 'Q3', 114234, 56793, 57441, 101.14098568485552, 220]
['III', 2021, 'Q3', 311728, 268460, 43268, 16.117112418982344, 637]
['ILINK', 2021, 'Q3', 246256, 221953, 24303, 10.949615459128735, 221]
['ILM', 2021, 'Q3', 445215, 534932, -89717, -16.771664435853527, 725]
['IMH', 2021, 'Q3', 290497, 85281, 205216, 240.63507698080463, 730]
['INET', 2021, 'Q3', 161658, 111220, 50438, 45.34975723790685, 223]
['INOX', 2021, 'Q3', 675829, 472680, 203149, 42.97812473555048, 674]
['INSET', 2021, 'Q3', 164135, 145396, 18739, 12.888250020633304, 738]
['INTUCH', 2021, 'Q3', 10801621, 10800542, 1079, 0.009990239378727476, 224]
['IP', 2021, 'Q3', 73677, 66424, 7253, 10.919246055642539, 736]
['IRC', 2021, 'Q3', 392322, 312902, 79420, 25.381748918191636, 225]
['IRPC', 2021, 'Q3', 13918559, 13319493, 599066, 4.4976636873490605, 227]
['IVL', 2021, 'Q3', 22206460, 16038471, 6167989, 38.45746268456638, 231]
['J', 2021, 'Q3', 58056, 78316, -20260, -25.869554114101845, 232]
['JAS', 2021, 'Q3', -2472905, -2897325, 424420, 14.648684562484359, 233]
['JASIF', 2021, 'Q3', 8129081, 8924412, -795331, -8.911858842913125, 234]
['JMART', 2021, 'Q3', 1106720, 1098107, 8613, 0.7843497946921383, 236]
['JMT', 2021, 'Q3', 1253443, 1184917, 68526, 5.783189877434453, 237]
['JTS', 2021, 'Q3', 166466, 74407, 92059, 123.72357439488219, 239]
['JUBILE', 2021, 'Q3', 206275, 272223, -65948, -24.22572670200534, 240]
['JWD', 2021, 'Q3', 471206, 404672, 66534, 16.441463703938002, 242]
['KAMART', 2021, 'Q3', 270164, 135737, 134427, 99.03489836964128, 243]
['KBANK', 2021, 'Q3', 41409930, 39457834, 1952096, 4.94729639746571, 245]
['KCE', 2021, 'Q3', 2105875, 1751778, 354097, 20.21357729118644, 249]
['KGI', 2021, 'Q3', 1945930, 2016345, -70415, -3.4922099144739613, 252]
['KKP', 2021, 'Q3', 5402784, 5271949, 130835, 2.481719758669896, 255]
['KSL', 2021, 'Q3', 563233, 703047, -139814, -19.886863893879074, 257]
['KTB', 2021, 'Q3', 20096874, 18099033, 1997841, 11.038385310419622, 258]
['KTC', 2021, 'Q3', 5952204, 5856336, 95868, 1.636996237920775, 259]
['LALIN', 2021, 'Q3', 1393010, 1361731, 31279, 2.297002858861258, 263]
['LANNA', 2021, 'Q3', 1312902, 639500, 673402, 105.30132916340891, 264]
['LH', 2021, 'Q3', 7278457, 8019935, -741478, -9.245436527852158, 267]
['LHFG', 2021, 'Q3', 1960994, 1765194, 195800, 11.092265212775478, 268]
['LHHOTEL', 2021, 'Q3', -391459, -269267, -122192, -45.37949321676997, 679]
['LIT', 2021, 'Q3', 20737, 38468, -17731, -46.092856400124774, 273]
['LPH', 2021, 'Q3', 467564, 230291, 237273, 103.0318162672445, 275]
['LPN', 2021, 'Q3', 513712, 589788, -76076, -12.898872137106892, 276]
['LST', 2021, 'Q3', 548673, 535883, 12790, 2.3867150105526767, 278]
['M', 2021, 'Q3', 81302, 803662, -722360, -89.8835580131946, 279]
['MAJOR', 2021, 'Q3', 2278649, 334383, 1944266, 581.4488176731472, 282]
['MAKRO', 2021, 'Q3', 6722588, 6723089, -501, -0.007451931693898445, 283]
['MBAX', 2021, 'Q3', 40794, 65277, -24483, -37.50631922422906, 288]
['MC', 2021, 'Q3', 466243, 450899, 15344, 3.4029793811917965, 291]
['MCS', 2021, 'Q3', 1288181, 1154845, 133336, 11.545791859513614, 293]
['MDX', 2021, 'Q3', 382593, 315715, 66878, 21.18302899767195, 294]
['MEGA', 2021, 'Q3', 1877717, 1607151, 270566, 16.83513247977321, 295]
['MFC', 2021, 'Q3', 298903, 268756, 30147, 11.217237940734346, 296]
['MFEC', 2021, 'Q3', 272513, 251641, 20872, 8.294355848212334, 297]
['MINT', 2021, 'Q3', -17200136, -22359811, 5159675, 23.07566463777355, 301]
['MSC', 2021, 'Q3', 162475, 166431, -3956, -2.3769610228863614, 313]
['MST', 2021, 'Q3', 805716, 690801, 114915, 16.63503671824447, 290]
['MTC', 2021, 'Q3', 5214552, 5353757, -139205, -2.600136689057796, 315]
['MTI', 2021, 'Q3', 716504, 691141, 25363, 3.6697287528883398, 314]
['NCH', 2021, 'Q3', 218968, 179207, 39761, 22.187191348552233, 317]
['NER', 2021, 'Q3', 1667199, 1379214, 287985, 20.880370993913925, 680]
['NNCL', 2021, 'Q3', 646661, 649046, -2385, -0.36746239865895486, 327]
['NOBLE', 2021, 'Q3', 1575515, 1949896, -374381, -19.200049643673303, 328]
['NRF', 2021, 'Q3', 120781, 109208, 11573, 10.597208995677972, 733]
['NYT', 2021, 'Q3', 272284, 256369, 15915, 6.207848842878819, 336]
['OISHI', 2021, 'Q3', 730662, 706204, 24458, 3.4633052205878188, 338]
['OR', 2021, 'Q3', 12043194, 13600759, -1557565, -11.452044698387787, 715]
['ORI', 2021, 'Q3', 3028548, 3036670, -8122, -0.2674640313237856, 339]
['OSP', 2021, 'Q3', 3254813, 3597950, -343137, -9.537014133047986, 681]
['PAP', 2021, 'Q3', 655840, 675988, -20148, -2.980526281531625, 342]
['PB', 2021, 'Q3', 1671240, 1570523, 100717, 6.412959249880454, 344]
['PCSGH', 2021, 'Q3', 661677, 583964, 77713, 13.307840894301703, 346]
['PDG', 2021, 'Q3', 63847, 66050, -2203, -3.335352006056018, 347]
['PDJ', 2021, 'Q3', 81732, 52215, 29517, 56.52973283539213, 371]
['PERM', 2021, 'Q3', 453054, 488821, -35767, -7.316993337029301, 350]
['PL', 2021, 'Q3', 111771, 97369, 14402, 14.791155295833375, 357]
['PLANB', 2021, 'Q3', 53022, 107629, -54607, -50.73632571147182, 358]
['PLE', 2021, 'Q3', -213019, -406498, 193479, 47.596544140438574, 360]
['POPF', 2021, 'Q3', 369438, 395816, -26378, -6.664207611617519, 364]
['PR9', 2021, 'Q3', 214433, 203676, 10757, 5.281427365030735, 682]
['PREB', 2021, 'Q3', 212139, 211003, 1136, 0.5383809708866699, 372]
['PRG', 2021, 'Q3', 424800, 414580, 10220, 2.4651454484056154, 374]
['PRM', 2021, 'Q3', 1646842, 1631954, 14888, 0.91228061575265, 639]
['PSH', 2021, 'Q3', 2192693, 2465527, -272834, -11.065950606097601, 377]
['PSL', 2021, 'Q3', 2730124, 1206757, 1523367, 126.23643368134596, 734]
['PTG', 2021, 'Q3', 1763890, 2209900, -446010, -20.182361192814156, 381]
['PTT', 2021, 'Q3', 93965796, 84433151, 9532645, 11.290168478966276, 383]
['PTTEP', 2021, 'Q3', 30745139, 28401949, 2343190, 8.250102836252541, 384]
['PTTGC', 2021, 'Q3', 48139410, 42042583, 6096827, 14.501551914638547, 385]
['QH', 2021, 'Q3', 1755538, 2067640, -312102, -15.094600607455844, 388]
['RATCH', 2021, 'Q3', 7778282, 8062394, -284112, -3.523916097377528, 394]
['RBF', 2021, 'Q3', 438351, 445699, -7348, -1.648646283702678, 703]
['RCL', 2021, 'Q3', 11122259, 7648135, 3474124, 45.42445968853845, 396]
['RICHY', 2021, 'Q3', 250028, 178798, 71230, 39.83825322430899, 398]
['RJH', 2021, 'Q3', 873088, 509206, 363882, 71.46066621367385, 399]
['ROJNA', 2021, 'Q3', 2184589, 1387048, 797541, 57.49916369152329, 404]
['RPC', 2021, 'Q3', 796080, 823738, -27658, -3.3576209911403874, 406]
['RS', 2021, 'Q3', 296042, 426994, -130952, -30.668346627821467, 408]
['RSP', 2021, 'Q3', 24184, 45397, -21213, -46.727757340793445, 659]
['S', 2021, 'Q3', -1966174, -2316938, 350764, 15.139118957865941, 410]
['S & J', 2021, 'Q3', 330438, 291383, 39055, 13.403321401728995, 693]
['S11', 2021, 'Q3', 397455, 409809, -12354, -3.014575082538451, 412]
['SAMTEL', 2021, 'Q3', -7982, -139490, 131508, 94.27772600186394, 418]
['SAPPE', 2021, 'Q3', 438058, 428831, 9227, 2.1516634758214774, 420]
['SAT', 2021, 'Q3', 1012725, 879018, 133707, 15.210951311577237, 421]
['SAUCE', 2021, 'Q3', 611283, 582235, 29048, 4.989050812816131, 422]
['SAWAD', 2021, 'Q3', 4867806, 4960214, -92408, -1.8629841373779439, 423]
['SC', 2021, 'Q3', 1938908, 2077963, -139055, -6.6918900865896065, 425]
['SCB', 2021, 'Q3', 32685706, 28509171, 4176535, 14.649794622228757, 426]
['SCC', 2021, 'Q3', 46914714, 49838986, -2924272, -5.867438795805356, 427]
['SCCC', 2021, 'Q3', 4117213, 4339222, -222009, -5.116331913877649, 428]
['SCGP', 2021, 'Q3', 7664850, 7219127, 445723, 6.174195300899957, 713]
['SENA', 2021, 'Q3', 995193, 1106986, -111793, -10.098863038918287, 437]
['SF', 2021, 'Q3', 2069519, 2214881, -145362, -6.5629711031879365, 438]
['SFLEX', 2021, 'Q3', 160962, 155105, 5857, 3.776151639212147, 731]
['SGP', 2021, 'Q3', 3833362, 3070469, 762893, 24.84613914030723, 441]
['SHANG', 2021, 'Q3', -1126073, -1152978, 26905, 2.3335224089271436, 442]
['SINGER', 2021, 'Q3', 611964, 564141, 47823, 8.47713603514015, 446]
['SIRI', 2021, 'Q3', 2262454, 2398926, -136472, -5.688879106733596, 447]
['SIS', 2021, 'Q3', 770111, 708470, 61641, 8.700580123364434, 449]
['SISB', 2021, 'Q3', 244084, 226723, 17361, 7.657361626301698, 683]
['SKN', 2021, 'Q3', 498309, 331135, 167174, 50.48514956135715, 642]
['SKR', 2021, 'Q3', 671172, 434395, 236777, 54.50730326085706, 451]
['SMART', 2021, 'Q3', 46257, 48474, -2217, -4.573585839831662, 453]
['SMPC', 2021, 'Q3', 565282, 578845, -13563, -2.3431143052112398, 455]
['SMT', 2021, 'Q3', 195971, 182434, 13537, 7.420217722573644, 456]
['SNC', 2021, 'Q3', 562811, 523773, 39038, 7.453228784225227, 457]
['SNP', 2021, 'Q3', 324563, 383674, -59111, -15.406569118574623, 694]
['SPALI', 2021, 'Q3', 6055750, 5552726, 503024, 9.059045953284928, 462]
['SPC', 2021, 'Q3', 1777920, 1684215, 93705, 5.563719596369822, 463]
['SPCG', 2021, 'Q3', 2512467, 2656472, -144005, -5.420911645219674, 464]
['SPG', 2021, 'Q3', 483045, 470525, 12520, 2.6608575527336487, 466]
['SPI', 2021, 'Q3', 3111018, 2774747, 336271, 12.118978775362223, 467]
['SPRC', 2021, 'Q3', 3754127, 3908828, -154701, -3.9577336224566544, 470]
['SPRIME', 2021, 'Q3', 403255, 516558, -113303, -21.934226166277554, 705]
['SQ', 2021, 'Q3', 380380, 375834, 4546, 1.2095765683785926, 472]
['SRICHA', 2021, 'Q3', 415164, 379882, 35282, 9.287620892803556, 474]
['SSP', 2021, 'Q3', 851710, 792740, 58970, 7.438756717208668, 643]
['SSSC', 2021, 'Q3', 209453, 149343, 60110, 40.24962669827176, 478]
['STA', 2021, 'Q3', 19731941, 18585573, 1146368, 6.1680530376975735, 481]
['STARK', 2021, 'Q3', 2319803, 1869756, 450047, 24.069825153656414, 735]
['STEC', 2021, 'Q3', 803325, 901757, -98432, -10.915579252503724, 484]
['STGT', 2021, 'Q3', 30384772, 30253877, 130895, 0.43265529241095285, 714]
['SUC', 2021, 'Q3', 907412, 1050623, -143211, -13.631055097784838, 486]
['SUPER', 2021, 'Q3', 2041485, 2004411, 37074, 1.849620661630773, 487]
['SUPEREIF', 2021, 'Q3', 392187, 527637, -135450, -25.671057943245074, 706]
['SUSCO', 2021, 'Q3', 313709, 330088, -16379, -4.962010130631832, 488]
['SVH', 2021, 'Q3', 1421797, 1461012, -39215, -2.6840984194517223, 490]
['SVI', 2021, 'Q3', 935897, 664787, 271110, 40.781483392424946, 491]
['SVOA', 2021, 'Q3', 171631, 157338, 14293, 9.08426444978327, 492]
['SYNEX', 2021, 'Q3', 764070, 740424, 23646, 3.1935755729149786, 495]
['TACC', 2021, 'Q3', 207646, 198551, 9095, 4.580687077879235, 498]
['TASCO', 2021, 'Q3', 2462389, 3946347, -1483958, -37.60333290508919, 502]
['TCAP', 2021, 'Q3', 4203625, 3509142, 694483, 19.790678177172655, 503]
['TCCC', 2021, 'Q3', 1548900, 1854143, -305243, -16.462753951556056, 506]
['TFFIF', 2021, 'Q3', 1086172, 1125581, -39409, -3.5012140396826172, 686]
['TFG', 2021, 'Q3', 847771, 2366035, -1518264, -64.16912683033007, 513]
['TFMAMA', 2021, 'Q3', 3662185, 3665530, -3345, -0.09125556195147769, 695]
['THANI', 2021, 'Q3', 1735286, 1806530, -71244, -3.943693157600483, 522]
['THE', 2021, 'Q3', 888883, 720774, 168109, 23.32339956768696, 524]
['THG', 2021, 'Q3', 732990, -24902, 757892, 3043.4985141755683, 661]
['THREL', 2021, 'Q3', 134762, 151692, -16930, -11.160773145584473, 526]
['TIPCO', 2021, 'Q3', 431040, 665709, -234669, -35.25098804432567, 530]
['TIPH', 2021, 'Q3', 2084102, 2263187, -179085, -7.912956375235454, 529]
['TISCO', 2021, 'Q3', 6626944, 6678026, -51082, -0.7649266414955557, 531]
['TK', 2021, 'Q3', 461919, 440632, 21287, 4.831015450534686, 532]
['TKN', 2021, 'Q3', 76824, 146473, -69649, -47.55074314037399, 533]
['TKS', 2021, 'Q3', 1147647, 366282, 781365, 213.32334103231938, 534]
['TMT', 2021, 'Q3', 1542586, 1357087, 185499, 13.668909951978023, 545]
['TNITY', 2021, 'Q3', 311293, 250253, 61040, 24.391315988219922, 549]
['TNPC', 2021, 'Q3', 144118, 150668, -6550, -4.347306661003, 552]
['TNR', 2021, 'Q3', 162623, 178618, -15995, -8.9548645713198, 553]
['TOA', 2021, 'Q3', 1975548, 2230973, -255425, -11.449040396275526, 645]
['TOG', 2021, 'Q3', 296941, 266740, 30201, 11.322261378121016, 554]

In [12]:
sql = """INSERT INTO qt_profits (name, year, quarter, latest_amt, previous_amt, \
inc_amt, inc_pct, ticker_id) \
 VALUES (?, ?, ?, ?, ?, ?, ?, ?)"""
print(sql)

INSERT INTO qt_profits (name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct, ticker_id)  VALUES (?, ?, ?, ?, ?, ?, ?, ?)

In [13]:
for rcd in rcds:
    conlt.execute(sql, rcd)

### End of loop

In [14]:
cols = ["name", "year", "quarter", "q_amt_c", "q_amt_p", "inc_profit", "Pct"]

criteria_1 = df_ins.q_amt_c > 440000
df_ins.loc[criteria_1, cols]

       name  year quarter   q_amt_c   q_amt_p  inc_profit         Pct
0        2S  2021      Q3    788297    725410       62887    8.669166
2       ACE  2021      Q3   1392091   1391075        1016    0.073037
3    ADVANC  2021      Q3  27223149  27361758     -138609   -0.506579
4        AH  2021      Q3   1041977   1109197      -67220   -6.060240
5       AIE  2021      Q3    522478    495054       27424    5.539598
..      ...   ...     ...       ...       ...         ...         ...
323     VNG  2021      Q3    782268    102807      679461  660.909277
324     VNT  2021      Q3   5991930   4263737     1728193   40.532355
326     WHA  2021      Q3   2009103   2277348     -268245  -11.778832
327   WHART  2021      Q3   2308085   2290736       17349    0.757355
328   WHAUP  2021      Q3    846412    828162       18250    2.203675

[197 rows x 7 columns]

In [15]:
criteria_2 = df_ins.q_amt_p > 400000
df_ins.loc[criteria_2, cols]

       name  year quarter   q_amt_c   q_amt_p  inc_profit         Pct
0        2S  2021      Q3    788297    725410       62887    8.669166
2       ACE  2021      Q3   1392091   1391075        1016    0.073037
3    ADVANC  2021      Q3  27223149  27361758     -138609   -0.506579
4        AH  2021      Q3   1041977   1109197      -67220   -6.060240
5       AIE  2021      Q3    522478    495054       27424    5.539598
..      ...   ...     ...       ...       ...         ...         ...
322     VIH  2021      Q3   1260420    462452      797968  172.551530
324     VNT  2021      Q3   5991930   4263737     1728193   40.532355
326     WHA  2021      Q3   2009103   2277348     -268245  -11.778832
327   WHART  2021      Q3   2308085   2290736       17349    0.757355
328   WHAUP  2021      Q3    846412    828162       18250    2.203675

[202 rows x 7 columns]

In [16]:
criteria_3 = df_ins.Pct > 10
df_ins.loc[criteria_3, cols]

       name  year quarter  q_amt_c  q_amt_p  inc_profit         Pct
14      AMC  2021      Q3   809057   665184      143873   21.629053
23      ASP  2021      Q3   907856   818663       89193   10.894959
24      AWC  2021      Q3  -597662 -1905093     1307431   68.628198
28      BAM  2021      Q3  2321436  2043406      278030   13.606205
29    BANPU  2021      Q3  5897490  1875967     4021523  214.370669
..      ...   ...     ...      ...      ...         ...         ...
322     VIH  2021      Q3  1260420   462452      797968  172.551530
323     VNG  2021      Q3   782268   102807      679461  660.909277
324     VNT  2021      Q3  5991930  4263737     1728193   40.532355
325  WACOAL  2021      Q3  -267916  -452435      184519   40.783538
329    WICE  2021      Q3   414565   308563      106002   34.353438

[108 rows x 7 columns]

In [17]:
df_ins_criteria = criteria_1 & criteria_2 & criteria_3
df_ins.loc[df_ins_criteria, cols]

       name  year quarter   q_amt_c   q_amt_p  inc_profit         Pct
14      AMC  2021      Q3    809057    665184      143873   21.629053
23      ASP  2021      Q3    907856    818663       89193   10.894959
28      BAM  2021      Q3   2321436   2043406      278030   13.606205
29    BANPU  2021      Q3   5897490   1875967     4021523  214.370669
31      BBL  2021      Q3  22586660  19694952     2891708   14.682483
32      BCH  2021      Q3   4644042   2161170     2482872  114.885548
33      BCP  2021      Q3   6119569   3652466     2467103   67.546228
35     BDMS  2021      Q3   7687881   6979197      708684   10.154234
37      BEC  2021      Q3    733898    651178       82720   12.703132
43       BH  2021      Q3    776568    702109       74459   10.605049
46      BLA  2021      Q3   3085271   2488156      597115   23.998294
55      CHG  2021      Q3   2644996   1363171     1281825   94.032590
56    CIMBT  2021      Q3   1531200    859475      671725   78.155269
58      CKP  2021      Q3   2064271   1660663      403608   24.304028
68      CRC  2021      Q3   3227788   1823748     1404040   76.986513
86   EGATIF  2021      Q3    639121    462260      176861   38.260070
98      GGC  2021      Q3    983347    839101      144246   17.190541
104    GULF  2021      Q3   6471046   5853218      617828   10.555356
107    HANA  2021      Q3   2303427   2059694      243733   11.833457
123    INOX  2021      Q3    675829    472680      203149   42.978125
129     IVL  2021      Q3  22206460  16038471     6167989   38.457463
137     JWD  2021      Q3    471206    404672       66534   16.441464
140     KCE  2021      Q3   2105875   1751778      354097   20.213577
144     KTB  2021      Q3  20096874  18099033     1997841   11.038385
147   LANNA  2021      Q3   1312902    639500      673402  105.301329
149    LHFG  2021      Q3   1960994   1765194      195800   11.092265
160   MBKET  2021      Q3    805716    690801      114915   16.635037
162     MCS  2021      Q3   1288181   1154845      133336   11.545792
164    MEGA  2021      Q3   1877717   1607151      270566   16.835132
172     NER  2021      Q3   1667199   1379214      287985   20.880371
184   PCSGH  2021      Q3    661677    583964       77713   13.307841
198     PSL  2021      Q3   2730124   1206757     1523367  126.236434
200     PTT  2021      Q3  93965796  84433151     9532645   11.290168
202   PTTGC  2021      Q3  48139410  42042583     6096827   14.501552
207     RCL  2021      Q3  11122259   7648135     3474124   45.424460
209     RJH  2021      Q3    873088    509206      363882   71.460666
210   ROJNA  2021      Q3   2184589   1387048      797541   57.499164
221     SAT  2021      Q3   1012725    879018      133707   15.210951
225     SCB  2021      Q3  32685706  28509171     4176535   14.649795
233     SGP  2021      Q3   3833362   3070469      762893   24.846139
241     SKR  2021      Q3    671172    434395      236777   54.507303
252     SPI  2021      Q3   3111018   2774747      336271   12.118979
260   STARK  2021      Q3   2319803   1869756      450047   24.069825
269     SVI  2021      Q3    935897    664787      271110   40.781483
274    TCAP  2021      Q3   4203625   3509142      694483   19.790678
280     THE  2021      Q3    888883    720774      168109   23.323400
291     TMT  2021      Q3   1542586   1357087      185499   13.668910
297     TOP  2021      Q3  14802781  13455400     1347381   10.013682
298   TPIPL  2021      Q3   3930600   3387423      543177   16.035110
301      TR  2021      Q3   4526722   3033058     1493664   49.246140
303     TSE  2021      Q3    694450    557201      137249   24.631865
321   VIBHA  2021      Q3   1436639    822576      614063   74.651218
322     VIH  2021      Q3   1260420    462452      797968  172.551530
324     VNT  2021      Q3   5991930   4263737     1728193   40.532355

In [18]:
df_ins[df_ins_criteria].sort_values(by=["Pct"], ascending=[False])

       name  year quarter   q_amt_c   q_amt_p  inc_profit         Pct   id
29    BANPU  2021      Q3   5897490   1875967     4021523  214.370669   47
322     VIH  2021      Q3   1260420    462452      797968  172.551530  611
198     PSL  2021      Q3   2730124   1206757     1523367  126.236434  734
32      BCH  2021      Q3   4644042   2161170     2482872  114.885548   51
147   LANNA  2021      Q3   1312902    639500      673402  105.301329  264
55      CHG  2021      Q3   2644996   1363171     1281825   94.032590   98
56    CIMBT  2021      Q3   1531200    859475      671725   78.155269  104
68      CRC  2021      Q3   3227788   1823748     1404040   76.986513  708
321   VIBHA  2021      Q3   1436639    822576      614063   74.651218  610
209     RJH  2021      Q3    873088    509206      363882   71.460666  399
33      BCP  2021      Q3   6119569   3652466     2467103   67.546228   52
210   ROJNA  2021      Q3   2184589   1387048      797541   57.499164  404
241     SKR  2021      Q3    671172    434395      236777   54.507303  451
301      TR  2021      Q3   4526722   3033058     1493664   49.246140  564
207     RCL  2021      Q3  11122259   7648135     3474124   45.424460  396
123    INOX  2021      Q3    675829    472680      203149   42.978125  674
269     SVI  2021      Q3    935897    664787      271110   40.781483  491
324     VNT  2021      Q3   5991930   4263737     1728193   40.532355  613
129     IVL  2021      Q3  22206460  16038471     6167989   38.457463  231
86   EGATIF  2021      Q3    639121    462260      176861   38.260070  156
233     SGP  2021      Q3   3833362   3070469      762893   24.846139  441
303     TSE  2021      Q3    694450    557201      137249   24.631865  573
58      CKP  2021      Q3   2064271   1660663      403608   24.304028  107
260   STARK  2021      Q3   2319803   1869756      450047   24.069825  735
46      BLA  2021      Q3   3085271   2488156      597115   23.998294   70
280     THE  2021      Q3    888883    720774      168109   23.323400  524
14      AMC  2021      Q3    809057    665184      143873   21.629053   22
172     NER  2021      Q3   1667199   1379214      287985   20.880371  680
140     KCE  2021      Q3   2105875   1751778      354097   20.213577  249
274    TCAP  2021      Q3   4203625   3509142      694483   19.790678  503
98      GGC  2021      Q3    983347    839101      144246   17.190541  188
164    MEGA  2021      Q3   1877717   1607151      270566   16.835132  295
160   MBKET  2021      Q3    805716    690801      114915   16.635037  290
137     JWD  2021      Q3    471206    404672       66534   16.441464  242
298   TPIPL  2021      Q3   3930600   3387423      543177   16.035110  559
221     SAT  2021      Q3   1012725    879018      133707   15.210951  421
31      BBL  2021      Q3  22586660  19694952     2891708   14.682483   50
225     SCB  2021      Q3  32685706  28509171     4176535   14.649795  426
202   PTTGC  2021      Q3  48139410  42042583     6096827   14.501552  385
291     TMT  2021      Q3   1542586   1357087      185499   13.668910  545
28      BAM  2021      Q3   2321436   2043406      278030   13.606205  709
184   PCSGH  2021      Q3    661677    583964       77713   13.307841  346
37      BEC  2021      Q3    733898    651178       82720   12.703132   56
252     SPI  2021      Q3   3111018   2774747      336271   12.118979  467
107    HANA  2021      Q3   2303427   2059694      243733   11.833457  205
162     MCS  2021      Q3   1288181   1154845      133336   11.545792  293
200     PTT  2021      Q3  93965796  84433151     9532645   11.290168  383
149    LHFG  2021      Q3   1960994   1765194      195800   11.092265  268
144     KTB  2021      Q3  20096874  18099033     1997841   11.038385  258
23      ASP  2021      Q3    907856    818663       89193   10.894959   40
43       BH  2021      Q3    776568    702109       74459   10.605049   61
104    GULF  2021      Q3   6471046   5853218      617828   10.555356  653
35     BDMS  2021      Q3   7687881   6979197      708684   10.154234   54
297     TOP  2021      Q3  14802781  13455400     1347381   10.013682  555

In [19]:
df_ins[df_ins_criteria].sort_values(by=["name"], ascending=[True])

       name  year quarter   q_amt_c   q_amt_p  inc_profit         Pct   id
14      AMC  2021      Q3    809057    665184      143873   21.629053   22
23      ASP  2021      Q3    907856    818663       89193   10.894959   40
28      BAM  2021      Q3   2321436   2043406      278030   13.606205  709
29    BANPU  2021      Q3   5897490   1875967     4021523  214.370669   47
31      BBL  2021      Q3  22586660  19694952     2891708   14.682483   50
32      BCH  2021      Q3   4644042   2161170     2482872  114.885548   51
33      BCP  2021      Q3   6119569   3652466     2467103   67.546228   52
35     BDMS  2021      Q3   7687881   6979197      708684   10.154234   54
37      BEC  2021      Q3    733898    651178       82720   12.703132   56
43       BH  2021      Q3    776568    702109       74459   10.605049   61
46      BLA  2021      Q3   3085271   2488156      597115   23.998294   70
55      CHG  2021      Q3   2644996   1363171     1281825   94.032590   98
56    CIMBT  2021      Q3   1531200    859475      671725   78.155269  104
58      CKP  2021      Q3   2064271   1660663      403608   24.304028  107
68      CRC  2021      Q3   3227788   1823748     1404040   76.986513  708
86   EGATIF  2021      Q3    639121    462260      176861   38.260070  156
98      GGC  2021      Q3    983347    839101      144246   17.190541  188
104    GULF  2021      Q3   6471046   5853218      617828   10.555356  653
107    HANA  2021      Q3   2303427   2059694      243733   11.833457  205
123    INOX  2021      Q3    675829    472680      203149   42.978125  674
129     IVL  2021      Q3  22206460  16038471     6167989   38.457463  231
137     JWD  2021      Q3    471206    404672       66534   16.441464  242
140     KCE  2021      Q3   2105875   1751778      354097   20.213577  249
144     KTB  2021      Q3  20096874  18099033     1997841   11.038385  258
147   LANNA  2021      Q3   1312902    639500      673402  105.301329  264
149    LHFG  2021      Q3   1960994   1765194      195800   11.092265  268
160   MBKET  2021      Q3    805716    690801      114915   16.635037  290
162     MCS  2021      Q3   1288181   1154845      133336   11.545792  293
164    MEGA  2021      Q3   1877717   1607151      270566   16.835132  295
172     NER  2021      Q3   1667199   1379214      287985   20.880371  680
184   PCSGH  2021      Q3    661677    583964       77713   13.307841  346
198     PSL  2021      Q3   2730124   1206757     1523367  126.236434  734
200     PTT  2021      Q3  93965796  84433151     9532645   11.290168  383
202   PTTGC  2021      Q3  48139410  42042583     6096827   14.501552  385
207     RCL  2021      Q3  11122259   7648135     3474124   45.424460  396
209     RJH  2021      Q3    873088    509206      363882   71.460666  399
210   ROJNA  2021      Q3   2184589   1387048      797541   57.499164  404
221     SAT  2021      Q3   1012725    879018      133707   15.210951  421
225     SCB  2021      Q3  32685706  28509171     4176535   14.649795  426
233     SGP  2021      Q3   3833362   3070469      762893   24.846139  441
241     SKR  2021      Q3    671172    434395      236777   54.507303  451
252     SPI  2021      Q3   3111018   2774747      336271   12.118979  467
260   STARK  2021      Q3   2319803   1869756      450047   24.069825  735
269     SVI  2021      Q3    935897    664787      271110   40.781483  491
274    TCAP  2021      Q3   4203625   3509142      694483   19.790678  503
280     THE  2021      Q3    888883    720774      168109   23.323400  524
291     TMT  2021      Q3   1542586   1357087      185499   13.668910  545
297     TOP  2021      Q3  14802781  13455400     1347381   10.013682  555
298   TPIPL  2021      Q3   3930600   3387423      543177   16.035110  559
301      TR  2021      Q3   4526722   3033058     1493664   49.246140  564
303     TSE  2021      Q3    694450    557201      137249   24.631865  573
321   VIBHA  2021      Q3   1436639    822576      614063   74.651218  610
322     VIH  2021      Q3   1260420    462452      797968  172.551530  611
324     VNT  2021      Q3   5991930   4263737     1728193   40.532355  613

In [20]:
df_ins[df_ins_criteria].sort_values(by=["name"], ascending=[True]).shape

(54, 8)